spring.application.name=sea-carpooling

spring.datasource.url=jdbc:postgresql://dpg-abc123-a.oregon-postgres.render.com:5432/sea_db
spring.datasource.username=root
spring.datasource.password=bannu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}